---
tls_enabled: false
mtls: false
mtls_ca:
  certificate: |
    -----BEGIN CERTIFICATE-----
    ... PLACE YOUR CERT HERE ...
    -----END CERTIFICATE-------
ultimate_ca:
  ca: |
    -----BEGIN CERTIFICATE-----
    ... PLACE YOUR CERT HERE ...
    -----END CERTIFICATE-------
  certificate: |
    -----BEGIN CERTIFICATE-----
    ... PLACE YOUR CERT HERE ...
    -----END CERTIFICATE-------
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    ... PLACE YOUR KEY HERE ...
    -----END RSA PRIVATE KEY-------
